services:
  besu:
    image: hyperledger/besu:latest
    container_name: besu-node
    volumes:
      - ./data:/var/lib/besu
      - ./genesis.json:/config/genesis.json
    command:
      [
        "--network=dev",
        "--rpc-http-enabled",
        "--rpc-http-api=ETH,NET,WEB3,TXPOOL",
        "--rpc-http-host=0.0.0.0",
        "--host-allowlist=*",
        "--rpc-http-cors-origins=*",
        "--miner-enabled",
        "--miner-coinbase=0xfe3b557e8fb62b89f4916b721be55ceb828dbd73",
        "--rpc-http-port=8545",
      ]
    ports:
      - "8545:8545"
